CREATE TABLE public.jobs (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  title TEXT NOT NULL,
  company TEXT NOT NULL,
  country TEXT NOT NULL,
  city TEXT,
  role_category TEXT NOT NULL,
  role_title_group TEXT,
  contract_type TEXT NOT NULL,
  duration TEXT,
  work_model TEXT NOT NULL,
  publication_date TIMESTAMPTZ NOT NULL,
  source TEXT,
  url TEXT,
  language JSONB NOT NULL DEFAULT '{}'::jsonb,
  match_score INTEGER NOT NULL DEFAULT 0,
  recommendation TEXT NOT NULL DEFAULT 'Maybe',
  match_summary TEXT,
  strong_matches TEXT[] NOT NULL DEFAULT '{}',
  partial_matches TEXT[] NOT NULL DEFAULT '{}',
  missing_requirements TEXT[] NOT NULL DEFAULT '{}',
  transferable_experience TEXT[] NOT NULL DEFAULT '{}',
  red_flags TEXT[] NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'New',
  date_added TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_verified TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.search_runs (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  search_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  search_criteria JSONB NOT NULL DEFAULT '{}'::jsonb,
  jobs_found INTEGER NOT NULL DEFAULT 0,
  jobs_added INTEGER NOT NULL DEFAULT 0,
  jobs_removed INTEGER NOT NULL DEFAULT 0
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.jobs TO anon, authenticated;
GRANT ALL ON public.jobs TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.search_runs TO anon, authenticated;
GRANT ALL ON public.search_runs TO service_role;

ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.search_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Jobs are publicly readable" ON public.jobs FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Jobs are publicly writable" ON public.jobs FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Jobs are publicly updatable" ON public.jobs FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Jobs are publicly deletable" ON public.jobs FOR DELETE TO anon, authenticated USING (true);

CREATE POLICY "Search runs are publicly readable" ON public.search_runs FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Search runs are publicly writable" ON public.search_runs FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE INDEX jobs_publication_date_idx ON public.jobs (publication_date DESC);
CREATE INDEX jobs_status_idx ON public.jobs (status);

INSERT INTO public.jobs (id,title,company,country,city,role_category,role_title_group,contract_type,duration,work_model,publication_date,source,url,language,match_score,recommendation,match_summary,strong_matches,partial_matches,missing_requirements,transferable_experience,red_flags,status,date_added,last_verified) VALUES
('job-001','Senior Technical Writer (API Documentation)','Nordcloud Systems','Sweden','Stockholm','Technical Writer','API Technical Writer','Contract','6 months + extension','Remote','2026-08-14T09:00:00.000Z','Client portal','https://example.com/jobs/job-001','{"working_language":"English","english_required":true,"local_language_required":false,"additional_languages":["Swedish (nice to have)"],"assessment":"Fully English-speaking engineering organisation. Swedish listed as a bonus only."}'::jsonb,94,'Apply','Remote API documentation contract in English with OpenAPI and docs-as-code tooling — an almost exact profile match.',ARRAY['OpenAPI / REST reference documentation ownership','Docs-as-code workflow (Git, Markdown, CI publishing)','English as the sole working language','Fully remote within EU time zones']::text[],ARRAY['Some developer-portal IA work expected','Occasional on-site workshops in Stockholm (2x per quarter)']::text[],ARRAY['Prior experience with Redocly specifically']::text[],ARRAY['Comparable static-site doc pipelines (Docusaurus, MkDocs)','Working directly with backend engineers on spec reviews']::text[],'{}'::text[],'New','2026-08-14T09:00:00.000Z','2026-08-14T09:00:00.000Z'),
('job-002','IT Business Analyst — Payments Platform','Helvetia Digital','Germany','Munich','Business Analyst','IT Business Analyst','Freelance','9 months','Hybrid','2026-08-13T09:00:00.000Z','Freelancer marketplace','https://example.com/jobs/job-002','{"working_language":"English","english_required":true,"local_language_required":false,"additional_languages":["German (preferred)"],"assessment":"Project language is English; German helpful for stakeholder small talk but not required."}'::jsonb,87,'Apply','Requirements work on a payments platform with an English project language and a long runway.',ARRAY['Requirements elicitation and user-story authoring','Cross-functional stakeholder facilitation','Long 9-month engagement']::text[],ARRAY['Payments domain knowledge assumed','Hybrid: 2 days on-site in Munich']::text[],ARRAY['SEPA / PSD2 regulatory background']::text[],ARRAY['Regulated-domain requirements work (insurance, health)','API-first product requirements']::text[],ARRAY['Rate not disclosed in the advert']::text[],'New','2026-08-14T09:00:00.000Z','2026-08-14T09:00:00.000Z'),
('job-003','Documentation Engineer','Aalborg Robotics','Denmark','Aalborg','Technical Writer','Documentation Engineer','Project-based','4 months','Hybrid','2026-08-12T09:00:00.000Z','Company careers page','https://example.com/jobs/job-003','{"working_language":"English","english_required":true,"local_language_required":false,"additional_languages":["Danish (optional)"],"assessment":"R&D department works entirely in English."}'::jsonb,82,'Apply','Docs tooling and pipeline ownership for a robotics SDK; strong tooling overlap, shorter duration.',ARRAY['Docs pipeline / CI ownership','SDK and developer-facing content','English-only working environment']::text[],ARRAY['Robotics/embedded domain','On-site 3 days per week']::text[],ARRAY['ROS ecosystem familiarity']::text[],ARRAY['Hardware-adjacent SDK documentation']::text[],ARRAY['Only 4 months with no stated extension']::text[],'New','2026-08-13T09:00:00.000Z','2026-08-13T09:00:00.000Z'),
('job-004','Requirements Engineer — Automotive Software','Stuttgart Mobility Works','Germany','Stuttgart','Business Analyst','Requirements Engineer','Contractor','12 months','Onsite','2026-08-11T09:00:00.000Z','Agency','https://example.com/jobs/job-004','{"working_language":"German","english_required":true,"local_language_required":true,"additional_languages":["English"],"assessment":"German is the primary working language for specification reviews — conflicts with the English-first criterion."}'::jsonb,54,'Don''t apply','Good technical fit but German is the mandatory working language and the role is fully on-site.',ARRAY['Requirements engineering with DOORS','Long engagement']::text[],ARRAY['Safety-critical specification experience']::text[],ARRAY['Native-level German','ASPICE process certification','Relocation to Stuttgart']::text[],ARRAY['Traceability matrices in regulated domains']::text[],ARRAY['German mandatory','Five days on-site','No remote allowance']::text[],'New','2026-08-12T09:00:00.000Z','2026-08-12T09:00:00.000Z'),
('job-005','Technical Author — Cloud Security','Helsinki Secure Labs','Finland','Helsinki','Technical Writer','Technical Author','Consulting assignment','6 months','Remote','2026-08-10T09:00:00.000Z','Consultancy broker','https://example.com/jobs/job-005','{"working_language":"English","english_required":true,"local_language_required":false,"additional_languages":["Finnish (not required)"],"assessment":"English-only documentation deliverables."}'::jsonb,91,'Apply','Fully remote English security documentation assignment with a clear deliverable scope.',ARRAY['Security product documentation','Fully remote across the Nordics','Clear deliverables and milestones','English-only']::text[],ARRAY['Compliance mapping content (ISO 27001)']::text[],ARRAY['Hands-on pentest background']::text[],ARRAY['IAM and cloud platform documentation']::text[],'{}'::text[],'New','2026-08-11T09:00:00.000Z','2026-08-11T09:00:00.000Z'),
('job-006','Business Analyst — Retail Data Platform','Lyon Commerce Group','France','Lyon','Business Analyst','Senior Business Analyst','Fixed-term','8 months','Hybrid','2026-08-09T09:00:00.000Z','Job board','https://example.com/jobs/job-006','{"working_language":"English","english_required":true,"local_language_required":false,"additional_languages":["French (preferred)"],"assessment":"Data team operates in English; French useful with retail stakeholders but not mandatory."}'::jsonb,76,'Maybe','Solid analyst fit, but heavier French stakeholder exposure and moderate on-site expectation.',ARRAY['Data platform requirements','Stakeholder workshops']::text[],ARRAY['French-speaking business users','Hybrid 2 days in Lyon']::text[],ARRAY['Retail merchandising domain','Conversational French']::text[],ARRAY['E-commerce analytics requirements','SQL profiling']::text[],ARRAY['Fixed-term employment rather than a freelance contract']::text[],'New','2026-08-10T09:00:00.000Z','2026-08-10T09:00:00.000Z'),
('job-007','Developer Documentation Writer','Copenhagen Fintech Core','Denmark','Copenhagen','Technical Writer','Developer Documentation Writer','Freelance','3 months + likely extension','Remote','2026-08-08T09:00:00.000Z','Client portal','https://example.com/jobs/job-007','{"working_language":"English","english_required":true,"local_language_required":false,"additional_languages":[],"assessment":"English only."}'::jsonb,88,'Apply','Developer portal rewrite for a fintech API platform — remote, English, strong tooling overlap.',ARRAY['Developer portal information architecture','API reference and tutorials','Remote-first team']::text[],ARRAY['Fintech compliance content']::text[],ARRAY['Danish market payment schemes']::text[],ARRAY['Payments API documentation elsewhere in the EU']::text[],ARRAY['Initial term only 3 months']::text[],'New','2026-08-09T09:00:00.000Z','2026-08-09T09:00:00.000Z'),
('job-008','Technical Requirements Engineer — MedTech','Uppsala Health Systems','Sweden','Uppsala','Business Analyst','Technical Requirements Engineer','Interim','7 months','Hybrid','2026-08-06T09:00:00.000Z','Agency','https://example.com/jobs/job-008','{"working_language":"English","english_required":true,"local_language_required":false,"additional_languages":["Swedish (nice to have)"],"assessment":"Regulatory documentation is authored in English."}'::jsonb,84,'Apply','Regulated requirements engineering with English documentation and a healthy duration.',ARRAY['Requirements traceability in a regulated setting','English documentation deliverables','7-month interim assignment']::text[],ARRAY['IEC 62304 lifecycle exposure','Hybrid, 2 days in Uppsala']::text[],ARRAY['Formal MDR audit participation']::text[],ARRAY['ISO-driven quality documentation']::text[],'{}'::text[],'New','2026-08-07T09:00:00.000Z','2026-08-07T09:00:00.000Z'),
('job-009','Documentation Specialist — Industrial IoT','Tampere Machine Cloud','Finland','Tampere','Technical Writer','Documentation Specialist','Temporary','5 months','Onsite','2026-08-05T09:00:00.000Z','Job board','https://example.com/jobs/job-009','{"working_language":"English","english_required":true,"local_language_required":false,"additional_languages":["Finnish (operators'' manuals)"],"assessment":"English is the source language, but some review cycles happen in Finnish."}'::jsonb,66,'Maybe','Reasonable content fit, held back by full on-site presence and partial Finnish review cycles.',ARRAY['Structured authoring','Industrial product documentation']::text[],ARRAY['Finnish review loops','DITA CCMS tooling']::text[],ARRAY['On-site presence in Tampere','Finnish reading ability']::text[],ARRAY['Manufacturing and hardware manuals']::text[],ARRAY['Fully on-site','Short 5-month term']::text[],'New','2026-08-06T09:00:00.000Z','2026-08-06T09:00:00.000Z'),
('job-010','Technical Business Analyst — Telecom OSS','Paris Network Partners','France','Paris','Business Analyst','Technical Business Analyst','Contract','10 months','Remote','2026-08-03T09:00:00.000Z','Consultancy broker','https://example.com/jobs/job-010','{"working_language":"English","english_required":true,"local_language_required":false,"additional_languages":["French (optional)"],"assessment":"Distributed team operating in English."}'::jsonb,79,'Maybe','Long remote contract with a good analyst fit; telecom OSS domain is the main gap.',ARRAY['Remote','Long duration','Systems analysis and integration specs']::text[],ARRAY['Telecom OSS/BSS domain','TM Forum standards']::text[],ARRAY['Prior OSS inventory project']::text[],ARRAY['Complex system integration requirements']::text[],'{}'::text[],'New','2026-08-04T09:00:00.000Z','2026-08-04T09:00:00.000Z'),
('job-011','Technical Writer — Developer Tools','Berlin Build Systems','Germany','Berlin','Technical Writer','Technical Writer','Freelance','6 months','Remote','2026-08-02T09:00:00.000Z','Company careers page','https://example.com/jobs/job-011','{"working_language":"English","english_required":true,"local_language_required":false,"additional_languages":[],"assessment":"English-only, globally distributed team."}'::jsonb,90,'Apply','Developer tooling documentation, fully remote, English-only, docs-as-code stack.',ARRAY['CLI and SDK documentation','Docs-as-code with Git review workflow','Fully remote freelance contract']::text[],ARRAY['Some DevRel-style content expected']::text[],ARRAY['Rust code sample authoring']::text[],ARRAY['Code sample authoring in Python and TypeScript']::text[],'{}'::text[],'New','2026-08-03T09:00:00.000Z','2026-08-03T09:00:00.000Z'),
('job-012','Requirements Manager — Public Sector Programme','Malmö Civic Digital','Sweden','Malmö','Business Analyst','Requirements Manager','Consulting assignment','12 months','Hybrid','2026-07-31T09:00:00.000Z','Public procurement portal','https://example.com/jobs/job-012','{"working_language":"Swedish","english_required":false,"local_language_required":true,"additional_languages":["English"],"assessment":"Procurement documentation must be produced in Swedish — fails the English working-language criterion."}'::jsonb,48,'Don''t apply','Attractive duration, but Swedish is mandatory for all deliverables.',ARRAY['Requirements management at programme level']::text[],ARRAY['Public sector governance']::text[],ARRAY['Professional Swedish','Swedish procurement experience']::text[],ARRAY['Large programme requirements governance']::text[],ARRAY['Swedish mandatory','Heavy procurement bureaucracy']::text[],'New','2026-08-01T09:00:00.000Z','2026-08-01T09:00:00.000Z');

INSERT INTO public.search_runs (id,search_date,search_criteria,jobs_found,jobs_added,jobs_removed) VALUES
('run-0','2026-08-14T09:00:00.000Z','{"roles":["Technical Writer","Business Analyst","Requirements Engineer"],"countries":["Germany","France","Sweden","Denmark","Finland"],"contract_types":["Contract","Freelance","Fixed-term","Temporary","Project-based"],"language":"English","max_age_days":15}'::jsonb,12,2,1),
('run-1','2026-08-13T09:00:00.000Z','{"roles":["Technical Writer","Business Analyst","Requirements Engineer"],"countries":["Germany","France","Sweden","Denmark","Finland"],"contract_types":["Contract","Freelance","Fixed-term","Temporary","Project-based"],"language":"English","max_age_days":15}'::jsonb,11,1,1),
('run-2','2026-08-12T09:00:00.000Z','{"roles":["Technical Writer","Business Analyst","Requirements Engineer"],"countries":["Germany","France","Sweden","Denmark","Finland"],"contract_types":["Contract","Freelance","Fixed-term","Temporary","Project-based"],"language":"English","max_age_days":15}'::jsonb,11,3,1),
('run-3','2026-08-10T09:00:00.000Z','{"roles":["Technical Writer","Business Analyst","Requirements Engineer"],"countries":["Germany","France","Sweden","Denmark","Finland"],"contract_types":["Contract","Freelance","Fixed-term","Temporary","Project-based"],"language":"English","max_age_days":15}'::jsonb,9,1,0),
('run-4','2026-08-07T09:00:00.000Z','{"roles":["Technical Writer","Business Analyst","Requirements Engineer"],"countries":["Germany","France","Sweden","Denmark","Finland"],"contract_types":["Contract","Freelance","Fixed-term","Temporary","Project-based"],"language":"English","max_age_days":15}'::jsonb,8,8,0);